In [1]:
with open('quran-simple.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [2]:
len(text)

735382

In [3]:
og_vocab = sorted(list(set(text)))
print(''.join(og_vocab))
print(len(og_vocab))
std_vocab = '0123456789|ءآأؤإئابةتثجحخدذرزسشصضطظعغـفقكلمنهوىي ۩'
std_vocab_size = len(std_vocab)
print(std_vocab_size)

reveries_vocab = 'ًٌٍَُِّْ'


 0123456789|ءآأؤإئابةتثجحخدذرزسشصضطظعغـفقكلمنهوىيًٌٍَُِّْٰۖۗۘۙۚۛۜ۩
67
50


In [4]:
text[:100]

'1|1|بِسْمِ اللَّهِ الرَّحْمَـٰنِ الرَّحِيمِ\n1|2|الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ\n1|3|الرَّحْمَـ'

In [5]:
def NextToken(index, text):
    if text[index] in numerics:
        token = [text[index],]
        j = index + 1
        while j < len(text) and text[j] in numerics:
            token.append(text[j])
            j += 1
            if text[j-1] == '|':
                break
        return ''.join(token), j
    elif text[index] in std_vocab:
        token = [text[index],]
        j = index + 1
        while j < len(text) and text[j] in reveries_vocab:
            token.append(text[j])
            j += 1
        return ''.join(token), j
    else:
        return text[index], index + 1

In [6]:
total = []
numerics = '0123456789|'
i = 0
test_text = text # text[:1000000]
while i < len(test_text):
    token, i = NextToken(i, test_text)
    # print(token)
    total.append(token)
print(len(total))

436583


In [7]:
actual_vocab = sorted(list(set(total)))
actual_vocab_size = len(actual_vocab)
actual_vocab_size, actual_vocab

(654,
 ['\n',
  ' ',
  '100|',
  '101|',
  '102|',
  '103|',
  '104|',
  '105|',
  '106|',
  '107|',
  '108|',
  '109|',
  '10|',
  '110|',
  '111|',
  '112|',
  '113|',
  '114|',
  '115|',
  '116|',
  '117|',
  '118|',
  '119|',
  '11|',
  '120|',
  '121|',
  '122|',
  '123|',
  '124|',
  '125|',
  '126|',
  '127|',
  '128|',
  '129|',
  '12|',
  '130|',
  '131|',
  '132|',
  '133|',
  '134|',
  '135|',
  '136|',
  '137|',
  '138|',
  '139|',
  '13|',
  '140|',
  '141|',
  '142|',
  '143|',
  '144|',
  '145|',
  '146|',
  '147|',
  '148|',
  '149|',
  '14|',
  '150|',
  '151|',
  '152|',
  '153|',
  '154|',
  '155|',
  '156|',
  '157|',
  '158|',
  '159|',
  '15|',
  '160|',
  '161|',
  '162|',
  '163|',
  '164|',
  '165|',
  '166|',
  '167|',
  '168|',
  '169|',
  '16|',
  '170|',
  '171|',
  '172|',
  '173|',
  '174|',
  '175|',
  '176|',
  '177|',
  '178|',
  '179|',
  '17|',
  '180|',
  '181|',
  '182|',
  '183|',
  '184|',
  '185|',
  '186|',
  '187|',
  '188|',
  '189|',
  '18|'

In [8]:
stoi = {ch:i for i,ch in enumerate(actual_vocab)}
itos = {i:ch for i,ch in enumerate(actual_vocab)}
# encode = lambda s: [stoi[ss] for ss in s]
def encode(text):
    i = 0
    total = []
    while i < len(text): 
        token, i = NextToken(i, text)
        total.append(stoi[token])
    return total
decode = lambda i: ''.join([itos[ii] for ii in i])
"إِيَادْ إِبْرَاهِيمْ", decode(encode("إِيَادْ إِبْرَاهِيمْ"))



('إِيَادْ إِبْرَاهِيمْ', 'إِيَادْ إِبْرَاهِيمْ')

In [142]:
# text.translate({ord(c): (c if c in vocab else None) for c in vocab})[:10]
# Not working for some reason.

TypeError: ord() expected a character, but string of length 4 found

In [9]:
import torch
data = torch.tensor(encode(text), dtype = torch.long)
print(data[:1000])

tensor([112, 112, 321, 450, 586,   1, 314, 566, 576, 613,   1, 314, 566, 424,
        379, 584, 524, 645, 600,   1, 314, 566, 424, 376, 632, 586,   0, 112,
        210, 314, 579, 374, 593, 394,   1, 572, 576, 613,   1, 418, 327,   1,
        314, 579, 509, 314, 570, 586, 632, 598,   0, 112, 221, 314, 566, 424,
        379, 584, 524, 645, 600,   1, 314, 566, 424, 376, 632, 586,   0, 112,
        232, 584, 314, 572, 558,   1, 635, 630, 586,   1, 314, 566, 401, 632,
        600,   0, 112, 243, 307, 641, 314, 556,   1, 598, 516, 320, 394,   1,
        621, 307, 641, 314, 556,   1, 598, 450, 339, 511, 632, 599,   0, 112,
        254, 314, 617, 395, 598, 314,   1, 314, 566, 470, 418, 314, 486,   1,
        314, 579, 585, 450, 339, 544, 632, 584,   0, 112, 265, 467, 418, 314,
        486,   1, 314, 576, 409, 632, 598,   1, 297, 606, 509, 593, 339,   1,
        509, 570, 644, 613, 593,   1, 520, 644, 420,   1, 314, 579, 584, 523,
        476, 618, 321,   1, 509, 570, 644, 613, 593,   1, 621, 5

In [12]:
n = int(0.9 * len(data))
# revisit this. Quran is complicated and end is probably the shorter verses which means training and validation are already diverting.
train_data = data[:n]
val_data = data[n:]

In [13]:
block_size = 8
train_data[:block_size + 1]

tensor([112, 112, 321, 450, 586,   1, 314, 566, 576])

In [14]:
x = train_data[:block_size]
y = train_data[1:block_size + 1]
x, y
context = []
for t in range(block_size):
    context = x[:t+1]
    print('input: ', context, ' and target: ', y[t])

input:  tensor([112])  and target:  tensor(112)
input:  tensor([112, 112])  and target:  tensor(321)
input:  tensor([112, 112, 321])  and target:  tensor(450)
input:  tensor([112, 112, 321, 450])  and target:  tensor(586)
input:  tensor([112, 112, 321, 450, 586])  and target:  tensor(1)
input:  tensor([112, 112, 321, 450, 586,   1])  and target:  tensor(314)
input:  tensor([112, 112, 321, 450, 586,   1, 314])  and target:  tensor(566)
input:  tensor([112, 112, 321, 450, 586,   1, 314, 566])  and target:  tensor(576)


In [15]:
torch.manual_seed(1337)
batch_size = 4 # how many independent sequences will we process in parallel?
block_size = 8 # what is the maximum context length for predictions?

def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

for b in range(batch_size): # batch dimension
    for t in range(block_size): # time dimension
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"when input is {context.tolist()} the target: {target}")

inputs:
torch.Size([4, 8])
tensor([[  1, 646,   1, 621, 314, 342, 543, 618],
        [618, 598,   1, 529, 341, 632, 567, 314],
        [585, 618, 443, 631, 645,   0, 123, 241],
        [  1, 529, 570, 314,   1, 339, 413, 611]])
targets:
torch.Size([4, 8])
tensor([[646,   1, 621, 314, 342, 543, 618, 314],
        [598,   1, 529, 341, 632, 567, 314,   0],
        [618, 443, 631, 645,   0, 123, 241, 529],
        [529, 570, 314,   1, 339, 413, 611, 328]])
----
when input is [1] the target: 646
when input is [1, 646] the target: 1
when input is [1, 646, 1] the target: 621
when input is [1, 646, 1, 621] the target: 314
when input is [1, 646, 1, 621, 314] the target: 342
when input is [1, 646, 1, 621, 314, 342] the target: 543
when input is [1, 646, 1, 621, 314, 342, 543] the target: 618
when input is [1, 646, 1, 621, 314, 342, 543, 618] the target: 314
when input is [618] the target: 598
when input is [618, 598] the target: 1
when input is [618, 598, 1] the target: 529
when input is [618, 5

In [16]:
import torch
import torch.nn as nn
from torch.nn import functional as F

torch.manual_seed(4337)

class BigramLanguageModule(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):
        logits = self.token_embedding_table(idx)
        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C) # I need to read on the cross_entropy function to understand why merging the B&T at the start removes the need
            # for the T at the end.
            loss = F.cross_entropy(logits, targets.view(B*T))
        return logits, loss
    
    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx


m = BigramLanguageModule(actual_vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)
print(decode(m.generate(torch.zeros((1,1), dtype=torch.long), max_new_tokens=1000)[0].tolist()))
    

torch.Size([32, 654])
tensor(7.0400, grad_fn=<NllLossBackward0>)

229|199|90|شٍصْمِّ101|صٌ274|عُّذًصٌاحً184|خَّبًئٍنَ6|بٌّدِعُلٍهٍ242|هٍ247|245|سٌطبُ236|ذْ145|1|زْ6|215|ثِ174|تًهسِّ140|187|هُ238|ذُرٌّذِكَّدٍّ238|79|127|بعً239|هجُّ12|110|ثَ194|حُأٌ165|12|سٌ196|يَّ246|142|صَّءِ42|دِّثِرِّفُّ97|229|144|56|207|كُ231|165|47|مُّبٍّذَثٌ116|سْ244|نٌّ258|مِسُ223|267|64|34|طٌنٍ24|231|
ث83|ذْبَّقِّ254|خِ41|22|219|بِ260|12|ءٍكُّكٌّنًكَّتَمٍّطُّ102|68|طكٍّ89|101|ظُمٌءٌخٍ244|95|ذْقًّؤِ14|25|144|بٍ103|مُكٌّ220|فِ52|ةَةً15|ذٌشِسِشْ44|247|156|69|عُّةُعٍ274|مٌحٌ136|62|شَّجَّ74|عًبْجَسْكَّهْدتًفٌ69|ذٌغِط262|دْجٌ177|قٍّعًّجٍّلُّبُّلً210|196|87|266|74|حُ247|242|بٌ125|م200|ثًّلُّذِ182|91|9|عُ126|109|جَكُ224|ثًضِّ265|140|مُّذَّمِ143|عٍفْ173|رٌّ36|228|ءِ214|253|59|180|243|ۜصَّ252|مِ176|ؤٌثٌقَ242|223|حٍؤِثً221|229|دِّ181|241|46|جٍوُّ58|وًّنِّ182|214|255|189|يٌّتُّضُّزَ269|22|183|158|فُّ37|221|صٌةَ70|31|قً139|142|276|41|كُّأْ123|96|17|182|
89|أُخْطَّأٌضَّوِ235|5|خُشِّذُ222|111|رمٍّ143|86|تُصًتًضَ40|212|44|198|أ

In [17]:
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [18]:
batch_size = 32
for steps in range(100000): # increase number of steps for good results...

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())

2.5949740409851074


In [19]:
print(decode(m.generate(torch.zeros((1,1), dtype=torch.long), max_new_tokens=1000)[0].tolist()))


36|4|75|وَالْبَاسِيَبْطِينَىٰكِتَثْلِي ا عَنَ رَّسُلُعِيكُلِّ سَلَئِمِندِيَالْأَتَيْهِنَّ عَذَانُونَ الشَّيْنَ
40|أَضَهُمْ الرِّبَكَالَىٰ فَتَ بِهِ مِن مَادْ تَطِيهًالْأَيَقُوا عَوْنُؤْمِ أَرْدُونَ فَالْإِذَهُمْ ال عَلَعْرِ
26|194|مَن ا أَقْتُم
9|36|فَضْلِقَبْعَمِلُهُمْ لَا هِ لَ الطُّونَا ادٍ صنَاحِيدَ فِيكُرُكُونَنَاتَّقُوا وَالرُّسُبْلِمِ ۖ لَ ا
41|37|140|ـٰ بِأَجِبَعُ مَ أَتَبِيهَ لَّهُ تَ كَارَنَّابِارِ ضَرَةِ ا أَ جُولِيهِ أَيْنَ يَكُمْ ثُمَّ تُثِيزٌ ا مِمَّ عَلْأَلِكُمْ يَدَنَّمَلَمِن عِيبٌ كِتَ إِلَّهَنَّاوَيُرِضُحًىٰكِرٍ
44|48|9|125|وَالْحَسِنِينِيدَتَ ۖ عَلَةً ۚ ۚ مَنَّ الْعَنْيَسْتَعَذَٰ اللَّةَ بِوَالَـٰلِكَا إِنَّ إِلَاجَّ قَوْلَىٰذَا بَعْرِكُم وَنَّ دَ قَدِرُونَ وَلَ لَّهُ فَرُ قَ لَقَوْمُواكٌ الَّهِ اسْجُلٌ يَتَخَرَقْوِزْوَمَ عَلُوبَعْدَجَمْ بِا خَبِادَةً فَا يَتَّبِمَنظُنُّبُيُظْلَاللَّمَرَ ابَ ۚ الَعَشِدُعَةً رُوبِنَصِيمِنَذِي مَا قُلْمٍ تَجْهِ أُوسَنَ فِينٍضَلَّتِ سَيَوْمٍ إِلَّهِ إِيَّ عِي مُوءٍ مَنْهُ سَفَلَ لِيَا إِنَّ يُؤْمِنَ
8|21|وَحَقُّوا إِلَّيْلِكُنزَنُذِيلَ